services:
  - type: web
    name: travel-agenticai
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SERPAPI_API_KEY
        value: your_serpapi_key_here  # Replace with your actual SERP API key
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here  # Replace with your actual OpenAI API key
      - key: STREAMLIT_SERVER_PORT
        value: "10000"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    numInstances: 1
    healthCheckPath: /
