services:
  - type: web
    name: travel-agenticai
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SERPAPI_API_KEY
        value: "05d7042d094556113f2b55287f8b20cf6af804b4b2c288c8b7c0c09e7bfacf9e" # This will be set in the Render dashboard
      - key: GOOGLE_API_KEY
        value: "AIzaSyACc6B-VlMgaw36jhxwKfGUzVPvsQfoNq8" # This will be set in the Render dashboard
      - key: STREAMLIT_SERVER_PORT
        value: "10000"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    numInstances: 1
    healthCheckPath: /
